# 参考博客地址
# https://www.cnblogs.com/sonyy/p/13157153.html
# https://blog.csdn.net/Lius_1006/article/details/107541988

version: "3"
services:
  prom:
    image: quay.io/prometheus/prometheus:latest
    volumes:
      - "./data/prometheus:/prometheus"
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    depends_on:
      - exporter
  exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
  #    network_mode: host
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: "always"
    depends_on:
      - prom