# docker-compose 的版本
version: '3'
services:

  redis:
    image: redis:5.0.0
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      # 数据文件
      - "./data:/data"
      # 配置文件
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
      # 服务器日志文件同步
      - "./log/redis-server.log:/var/log/redis/redis-server.log"